application: steadfast-icon-97115
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: guestbook.app
  
libraries:
- name: webapp2
  version: latest
